import type { Metadata } from "next";
import Cabecalho  from "@/components/Cabecalho";
import localFont from "next/font/local";
import "./globals.css";
import Rodape from "@/components/Rodape";
import CadMecanico from "@/CadMecanico/page";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Cabecalho/>
        {CadMecanico}
        <Rodape/>
      </body>
    </html>
  )
}
